# Generated by Django 4.2.11 on 2024-03-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_alter_registrationorder_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(error_messages={'unique': 'A user with that client_id already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, verbose_name='client_id')),
                ('attempts', models.IntegerField(default=0, verbose_name='Неудачные попытки входа')),
            ],
        ),
    ]
